version: '3.8'

services:
  scraper-base:
    build:
      context: ./scraper-base
      dockerfile: Dockerfile
    image: cityagent-scraper-base:latest
    container_name: scraper_base_usetravel

  elife_scraper_usetravel:
    build:
      context: ./elife_scraper
      dockerfile: Dockerfile
    image: cityagent-elife-scraper:latest
    container_name: elife_scraper_usetravel
    depends_on:
      - scraper-base
    env_file: .env.client_usetravel
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  wt_scraper_usetravel:
    build:
      context: ./wt_scraper
      dockerfile: Dockerfile
    image: cityagent-wt-scraper:latest
    container_name: wt_scraper_usetravel
    depends_on:
      - scraper-base
    env_file: .env.client_usetravel
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  analyzer_usetravel:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    image: cityagent-analyzer:latest
    container_name: analyzer_usetravel
    env_file: .env.client_usetravel
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  geo_usetravel:
    build:
      context: ./geo
      dockerfile: Dockerfile
    image: cityagent-geo:latest
    container_name: geo_usetravel
    env_file: .env.client_usetravel
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  match_usetravel:
    build:
      context: ./match
      dockerfile: Dockerfile
    image: cityagent-match:latest
    container_name: match_usetravel
    env_file: .env.client_usetravel
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  dashboard_usetravel:
    build:
      context: ./gui
      dockerfile: Dockerfile
    image: cityagent-dashboard:latest
    container_name: dashboard_usetravel
    env_file: .env.client_usetravel
    volumes:
      - ./utils:/app/utils:ro
    ports:
      - "8502:8501"  # localhost:8502 → container:8501
    restart: always
