version: '3.8'
services:
  analyzer:
    build: ./analyzer
    env_file: .env
    mem_limit: 512m
    cpus: 0.25
    restart: always

  calendar_scraper:
    build: ./calendar_scraper
    env_file: .env
    mem_limit: 512m
    cpus: 0.25
    restart: always

  elife_scraper:
    build: ./elife_scraper
    env_file: .env
    mem_limit: 512m
    cpus: 0.25
    restart: always

  geo:
    build: ./geo
    env_file: .env
    mem_limit: 512m
    cpus: 0.25
    restart: always

  match:
    build: ./match
    env_file: .env
    mem_limit: 512m
    cpus: 0.25
    restart: always

  wt_scraper:
    build: ./wt_scraper
    env_file: .env
    mem_limit: 512m
    cpus: 0.25
    restart: always

