version: '3.8'

services:
  scraper-base:
    build:
      context: .
      dockerfile: ./scraper-base/Dockerfile
    image: cityagent-scraper-base:latest

  elife_scraper:
    build:
      context: .
      dockerfile: ./elife_scraper/Dockerfile
    image: cityagent-elife-scraper:latest
    depends_on:
      - scraper-base
    env_file: .env
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  wt_scraper:
    build:
      context: .
      dockerfile: ./wt_scraper/Dockerfile
    image: cityagent-wt-scraper:latest
    depends_on:
      - scraper-base
    env_file: .env
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  analyzer:
    build:
      context: .
      dockerfile: ./analyzer/Dockerfile
    image: cityagent-analyzer:latest
    env_file: .env
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  calendar_scraper:
    build:
      context: .
      dockerfile: ./calendar_scraper/Dockerfile
    image: cityagent-calendar-scraper:latest
    env_file: .env
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  geo:
    build:
      context: .
      dockerfile: ./geo/Dockerfile
    image: cityagent-geo:latest
    env_file: .env
    volumes:
      - ./utils:/app/utils:ro
    restart: always

  match:
    build:
      context: .
      dockerfile: ./match/Dockerfile
    image: cityagent-match:latest
    env_file: .env
    volumes:
      - ./utils:/app/utils:ro
    restart: always
